server:
  port: 7078
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:7077/eureka
zuul:
   routes:
    hello:
      path: /**
      url: http://localhost:7079
      service-id:  hello
      customSensitiveHeaders: true
   ws:
      brokerages:
        hello:
          end-points: /gs-guide-websocket
          brokers:  /topic
          destination-prefixes: /app
